---
driver:
  name: vagrant
  
provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-6
    driver_config:
      network:
      - ["forwarded_port", {guest: 3000, host: 3000}] # grafana
      - ["forwarded_port", {guest: 9090, host: 9090}] # prometheus
      - ["forwarded_port", {guest: 9100, host: 9100}] # node_exporter
suites:
  - name: default
    run_list:
      - recipe[prometheus::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
